# Generated by Django 3.0.7 on 2020-06-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('label', models.CharField(blank=True, max_length=20)),
                ('probability', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ORM_Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_nombre', models.CharField(max_length=50)),
                ('imagen_porcentaje', models.FloatField()),
                ('imagen_prediccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pclass', models.IntegerField()),
                ('sex', models.CharField(max_length=6)),
                ('age', models.IntegerField()),
                ('fare', models.FloatField()),
                ('embarked', models.CharField(max_length=1)),
                ('survived', models.CharField(blank=True, max_length=1)),
            ],
        ),
    ]
