# Generated by Django 3.0.7 on 2020-06-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSNN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orm_imagen',
            name='imagen_nombre',
            field=models.CharField(max_length=45),
        ),
    ]
