# Generated by Django 3.0.7 on 2020-06-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSNN', '0002_auto_20200607_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='orm_imagen',
            name='imagen_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
