# Generated by Django 3.0.7 on 2020-06-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSNN', '0003_orm_imagen_imagen_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orm_imagen',
            name='id',
        ),
        migrations.AlterField(
            model_name='orm_imagen',
            name='imagen_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
